import json
import sys
import random as rand


'''
cleanUpString:
	Purpose: Helper function to clean up the proceeding/trailing text from gpt responses.
	Params: dirtyStr: string to be "cleaned up"
	Returns: "clean" string ready to be turned to JSON
'''
def cleanUpString(dirtyStr):
	begin = dirtyStr.find('[')
	end = dirtyStr.rfind(']')
	return dirtyStr[begin:end+1]


'''
formatFlashcard:
	Purpose: Takes a response from gpt-4 and formats it for printing by discord bot.
	Params: response: response string generated by gpt-4.
	Returns: List of Strings formated for discord markdown.
'''
def formatFlashcard(response):
	#Iterate through the list of dictionaries, formating them and placing the formated string in a list
	final = []
	#Remove preciding and trailing text from the gpt response string
	clean = cleanUpString(response)
	for card in json.loads(clean):
		front = card["front"]
		back = card["back"]
		final.append(f'{front}\n\n||{back}||')

	return final


'''
'''
def formatKahoot(response):
	#Iterate through the list of disctionaries, formating them and placing the formated string in a list
	final = []
	#Remove preciding and trailing text from the gpt response string
	clean = cleanUpString(response)
	for quest in json.loads(clean):
		question = quest["question"]
		answer = quest["answer"]
		fakes = quest["fake_answers"]
		#insert answer into fakes at a random index
		fakes.insert(rand.randint(0, 3), answer)

		final.append(f'**{question}**\n1. {fakes[0]}\n2. {fakes[1]}\n3. {fakes[2]}\n4. {fakes[3]}')
		final.append(answer)
	return final

'''
[{"question": "<question>",
"answer": "<correct answer to the question>",
"fake_answers": [
	"<fake 1>",
	"<fake 2>",
	"<fake 3>"
]},
...]
'''


#print(formatFlashcard(testDict1))
#print(formatFlashcard(testDict2))



